"""empty message

Revision ID: 080c4d08ca20
Revises: 9137ef899882
Create Date: 2024-05-31 18:04:37.969531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080c4d08ca20'
down_revision = '9137ef899882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
