"""empty message

Revision ID: 122830e8f656
Revises: 080c4d08ca20
Create Date: 2024-05-31 18:08:12.116213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122830e8f656'
down_revision = '080c4d08ca20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###
