"""empty message

Revision ID: 9a90a9d86caa
Revises: 
Create Date: 2024-06-10 13:56:20.415424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a90a9d86caa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('rol', sa.Boolean(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('perfil_entrenador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_entrenador_id', sa.Integer(), nullable=False),
    sa.Column('tipo_entrenamiento', sa.String(length=100), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('genero', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['user_entrenador_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perfil_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('genero', sa.String(length=10), nullable=True),
    sa.Column('peso', sa.String(length=30), nullable=True),
    sa.Column('altura', sa.String(length=30), nullable=True),
    sa.Column('foto', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asignacion_entrenador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrenador_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entrenador_id'], ['perfil_entrenador.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['perfil_usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asignacion_entrenador')
    op.drop_table('perfil_usuario')
    op.drop_table('perfil_entrenador')
    op.drop_table('user')
    # ### end Alembic commands ###
