"""empty message

Revision ID: 9ad1e0a71d57
Revises: c5fde36423c8
Create Date: 2024-06-07 19:26:48.228495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ad1e0a71d57'
down_revision = 'c5fde36423c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entrenador', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('apellido',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('tipo_entrenamiento',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('edad',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('genero',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entrenador', schema=None) as batch_op:
        batch_op.alter_column('genero',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('edad',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('tipo_entrenamiento',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('apellido',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
