"""empty message

Revision ID: b2fa9dfd748c
Revises: a6f00e5786b0
Create Date: 2024-06-07 15:48:34.994354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2fa9dfd748c'
down_revision = 'a6f00e5786b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entrenador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genero', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entrenador', schema=None) as batch_op:
        batch_op.drop_column('genero')

    # ### end Alembic commands ###
