"""empty message

Revision ID: bd0648011695
Revises: 6aa4ac712c1e
Create Date: 2024-05-29 19:42:12.853663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd0648011695'
down_revision = '6aa4ac712c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=80), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('is_trainer',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_constraint('user_nombre_key', type_='unique')
        batch_op.drop_constraint('user_telefono_key', type_='unique')
        batch_op.drop_column('nombre')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('telefono')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('user_telefono_key', ['telefono'])
        batch_op.create_unique_constraint('user_nombre_key', ['nombre'])
        batch_op.alter_column('is_trainer',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('password')

    # ### end Alembic commands ###
