"""tabla arreglada1

Revision ID: c5fde36423c8
Revises: b2fa9dfd748c
Create Date: 2024-06-07 16:18:37.352385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5fde36423c8'
down_revision = 'b2fa9dfd748c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entrenador', schema=None) as batch_op:
        batch_op.alter_column('genero',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entrenador', schema=None) as batch_op:
        batch_op.alter_column('genero',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
