"""empty message

Revision ID: ecfa9bc9d048
Revises: 406f5e1a77a6
Create Date: 2024-05-30 19:33:50.946289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecfa9bc9d048'
down_revision = '406f5e1a77a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=120), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
