"""empty message

Revision ID: f6ee71fc9da7
Revises: 64f67f591165
Create Date: 2024-05-31 16:43:49.951980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6ee71fc9da7'
down_revision = '64f67f591165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('is_trainer',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_constraint('user_correo_key', type_='unique')
        batch_op.drop_constraint('user_nombre_key', type_='unique')
        batch_op.drop_constraint('user_telefono_key', type_='unique')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('correo')
        batch_op.drop_column('nombre')
        batch_op.drop_column('telefono')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('correo', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_telefono_key', ['telefono'])
        batch_op.create_unique_constraint('user_nombre_key', ['nombre'])
        batch_op.create_unique_constraint('user_correo_key', ['correo'])
        batch_op.alter_column('is_trainer',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('email')

    # ### end Alembic commands ###
