"""empty message

Revision ID: fba2fc28e105
Revises: 32f3655bdb91
Create Date: 2024-05-31 17:32:58.713899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fba2fc28e105'
down_revision = '32f3655bdb91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', sa.Boolean(), nullable=False))
        batch_op.drop_column('is_trainer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_trainer', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('rol')

    # ### end Alembic commands ###
